FROM ubuntu:latest
FROM python:3.9-slim

SHELL ["/bin/bash", "-c"]

WORKDIR /replier
COPY . /replier

EXPOSE 5672
EXPOSE 8080

RUN python3 -m venv venv && source venv/bin/activate
RUN pip3 install -r requirements.txt

CMD python3 -m src.rabbitmq_tools.consumer
